CREATE DATABASE IF NOT EXISTS alumnos;

USE alumnos;


CREATE TABLE IF NOT EXISTS alumno(
id INT NOT NULL UNIQUE AUTO_INCREMENT,
nombre VARCHAR(30) NOT NULL,
apellidos VARCHAR(30) NOT NULL,
rut VARCHAR(13) NOT NULL UNIQUE,
curso VARCHAR(200) NOT NULL,
grupo VARCHAR(50),
rol VARCHAR(30),
chequeo VARCHAR(30),
PRIMARY KEY(id)
)ENGINE=INNODB;





