CREATE DATABASE IF NOT EXISTS archivo;

USE archivo;


CREATE TABLE IF NOT EXISTS archivos(
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(255) NOT NULL,
tamaño INT NOT NULL,
descargas INT NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB;

