CREATE DATABASE IF NOT EXISTS login_curso;

USE login_curso;


CREATE TABLE IF NOT EXISTS usuarios(
id INT NOT NULL UNIQUE AUTO_INCREMENT,
usuario VARCHAR(30) NOT NULL,
password VARCHAR(150) NOT NULL,
tipo_usuario VARCHAR(30) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB;



