CREATE DATABASE IF NOT EXISTS rol;

USE rol;

CREATE TABLE IF NOT EXISTS roles(
idr INT NOT NULL UNIQUE AUTO_INCREMENT,
rol VARCHAR(30) NOT NULL,
PRIMARY KEY(idr)
)ENGINE=INNODB;


INSERT INTO roles (idr,rol) VALUES (NULL,'Supervisor');
INSERT INTO roles (idr,rol) VALUES (NULL,'Programador');

